version: 0.2
env:
  parameter-store:
     gitguardianApiKey: "GITGUARDIAN_API_KEY"
   
phases:
#   pre_build:
#     commands:
#       - sudo yum update -y
#       - sudo amazon-linux-extras install docker
#       - apt update
#       - apt install apt
#       - sudo apt-get install sysvinit-utils
#       - sudo service docker start
#       - sudo usermod -a -G docker ec2-user
#   build:
#     commands:
#       - echo Build started on `date`
#       - echo Building the Docker image...
#       - docker pull gitguardian/ggshield:latest
#       - docker run --name ggshieldcli gitguardian/ggshield:latest
#       - ggshield secret scan ci
  install:
    commands:
      - pip install ggshield
  build:
    commands:
      - curl -H "Authorization: Token $gitguardianApiKey" https://api.gitguardian.com/v1/health
      - ggshield secret scan repo sample_secrets
  



# container:
#   image: gitguardian/ggshield:latest
#   options: -u 0

# steps:
# - script: ggshield secret scan ci
#   env:
#     GITGUARDIAN_API_KEY: $gitguardianApiKey

# sudo yum install -y docker
#       - sudo systemctl enable docker
#       - sudo systemctl start docker
#       - sudo usermod -a -G docker awsuser
