version: 0.2
env:
  parameter-store:
     gitguardianApiKey: "GITGUARDIAN_API_KEY"
   
phases:
  build:
    commands:
      - echo some commands will be added
  post_build:
    commands:
      - ggshield secret scan ci gitguardianApiKey
  
artifacts:
  files:
  - '.txt'
  name: gitguardian_results-$(date +%Y-%m-%d)
  


# phases:
#   install:
#       commands:
#         - pip install ggshield
#   build:
#       commands:
#         - ggshield secret scan ci
#           env:
#             gitguardianApiKey
    

# container:
#   image: gitguardian/ggshield:latest
#   options: -u 0

# steps:
# - script: ggshield secret scan ci
#   env:
#     GITGUARDIAN_API_KEY: $gitguardianApiKey

# sudo yum install -y docker
#       - sudo systemctl enable docker
#       - sudo systemctl start docker
#       - sudo usermod -a -G docker awsuser
