version: 0.2
env:
  parameter-store:
     gitguardianApiKey: "GITGUARDIAN_API_KEY"
   
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
#       - docker pull gitguardian/ggshield:latest
#       - docker run --name ggshieldcli gitguardian/ggshield:latest
      - ggshield auth login --method=token
      - ggshield secret scan
  



# container:
#   image: gitguardian/ggshield:latest
#   options: -u 0

# steps:
# - script: ggshield secret scan ci
#   env:
#     GITGUARDIAN_API_KEY: $gitguardianApiKey

# sudo yum install -y docker
#       - sudo systemctl enable docker
#       - sudo systemctl start docker
#       - sudo usermod -a -G docker awsuser
