version: 0.2
env:
  parameter-store:
     gitguardianApiKey: GITGUARDIAN_API_KEY
    
phases:
  pre_build:
    commands:
      - sudo dnf install yum
      - sudo yum update -y
      - sudo yum install -y docker
      - sudo service docker start
      - sudo usermod -a -G docker awsuser
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker pull gitguardian/ggshield:latest
      - docker run --name ggshieldcli gitguardian/ggshield:latest
  post_build:
    commands:
      - ggshield secret scan ci --apikey $gitguardianApiKey

# container:
#   image: gitguardian/ggshield:latest
#   options: -u 0

# steps:
# - script: ggshield secret scan ci
#   env:
#     GITGUARDIAN_API_KEY: $gitguardianApiKey
